browser: chrome
login: orangemouse807
address: https://speller.yandex.net/services/spellservice?WSDL
url: https://test-stand.gb.ru/gateway/login
password: a4f8fb1d99
api: https://test-stand.gb.ru/api/posts
title: post from pycharm